# This file was automatically generated by passthru.fetch-deps.
# Please dont edit it manually, your changes might get overwritten!
{fetchNuGet}: [
  (fetchNuGet {
    pname = "FreeTypeSharp";
    version = "2.0.0.12-ci";
    sha256 = "1bjh15wpzv45nm45bp23h7zgx8bc3l3nfpssbmsp4n02g642jmnw";
  })
  (fetchNuGet {
    pname = "Microsoft.Bcl.AsyncInterfaces";
    version = "6.0.0";
    sha256 = "15gqy2m14fdlvy1g59207h5kisznm355kbw010gy19vh47z8gpz3";
  })
  (fetchNuGet {
    pname = "Microsoft.CSharp";
    version = "4.7.0";
    sha256 = "0gd67zlw554j098kabg887b5a6pq9kzavpa3jjy5w53ccjzjfy8j";
  })
  (fetchNuGet {
    pname = "Microsoft.DotNet.PlatformAbstractions";
    version = "3.1.6";
    sha256 = "0b9myd7gqbpaw9pkd2bx45jhik9mwj0f1ss57sk2cxmag2lkdws5";
  })
  (fetchNuGet {
    pname = "Microsoft.Extensions.DependencyModel";
    version = "6.0.0";
    sha256 = "08c4fh1n8vsish1vh7h73mva34g0as4ph29s4lvps7kmjb4z64nl";
  })
  (fetchNuGet {
    pname = "Microsoft.NETCore.Platforms";
    version = "5.0.0";
    sha256 = "0mwpwdflidzgzfx2dlpkvvnkgkr2ayaf0s80737h4wa35gaj11rc";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Threading";
    version = "17.1.46";
    sha256 = "0w7b17xh88rqzjjsy66gg2kfaqmg7sdmx70sharkqb7qh3pih87m";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Threading.Analyzers";
    version = "17.1.46";
    sha256 = "0lgx7776ivmz0gr0whyacxpnlp6w5b80mj012a28mm79r1qxpf60";
  })
  (fetchNuGet {
    pname = "Microsoft.VisualStudio.Validation";
    version = "17.0.53";
    sha256 = "0y34dvc5z6ash2cpp69mclb3wr52fd8khsmm61sv7lkql0pg03ki";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.Registry";
    version = "5.0.0";
    sha256 = "102hvhq2gmlcbq8y2cb7hdr2dnmjzfp2k3asr1ycwrfacwyaak7n";
  })
  (fetchNuGet {
    pname = "Microsoft.Win32.SystemEvents";
    version = "5.0.0";
    sha256 = "0sja4ba0mrvdamn0r9mhq38b9dxi08yb3c1hzh29n1z6ws1hlrcq";
  })
  (fetchNuGet {
    pname = "Nerdbank.Streams";
    version = "2.9.112";
    sha256 = "1i10xr5zm9vapfzvimim9gn2pm9vgnsnb44sq3b0162r0k572rrp";
  })
  (fetchNuGet {
    pname = "Newtonsoft.Json";
    version = "13.0.1";
    sha256 = "0fijg0w6iwap8gvzyjnndds0q4b8anwxxvik7y8vgq97dram4srb";
  })
  (fetchNuGet {
    pname = "OVRSharp";
    version = "1.2.0";
    sha256 = "123y7ad236q028gvd80khb5lx9xmhmx6x8q6pwx35jb4kx8vs0n5";
  })
  (fetchNuGet {
    pname = "Silk.NET.Core";
    version = "2.16.0";
    sha256 = "1mkqc2aicvknmpyfry2v7jjxh3apaxa6dmk1vfbwxnkysl417x0k";
  })
  (fetchNuGet {
    pname = "Silk.NET.GLFW";
    version = "2.16.0";
    sha256 = "17y83af5p2sviyx5g1ckqf60qv46wsnqympa2xz9zxmkqxpcl9k8";
  })
  (fetchNuGet {
    pname = "Silk.NET.Maths";
    version = "2.16.0";
    sha256 = "0lkap7h0xvsg60h0wjiyczr0fxqwfsxk4wlwkhfsxv12v3w44sq6";
  })
  (fetchNuGet {
    pname = "Silk.NET.OpenGL";
    version = "2.16.0";
    sha256 = "1xfpj4266xfbgqkifyzivmhrj9wm4bm1mapjgxq72jwv4l4d62rj";
  })
  (fetchNuGet {
    pname = "Silk.NET.Windowing.Common";
    version = "2.16.0";
    sha256 = "1ry0dh3bgf4rhij50a31ya5axyali126yk9a9b9d9170kzhnymxn";
  })
  (fetchNuGet {
    pname = "Silk.NET.Windowing.Glfw";
    version = "2.16.0";
    sha256 = "1ar5ip3xp7qqx1pg82k0xrl8jldvq5mmgmbdzrmvwb7azspzs736";
  })
  (fetchNuGet {
    pname = "SixLabors.ImageSharp";
    version = "2.1.3";
    sha256 = "12qb0r7v2v91vw8q8ygr67y527gwhbas6d6zdvrv4ksxwjx9dzp9";
  })
  (fetchNuGet {
    pname = "System.Buffers";
    version = "4.5.1";
    sha256 = "04kb1mdrlcixj9zh1xdi5as0k0qi8byr5mi3p3jcxx72qz93s2y3";
  })
  (fetchNuGet {
    pname = "System.Drawing.Common";
    version = "5.0.0";
    sha256 = "0fag8hr2v9bswrsjka311lhbr1a43yzcc36j4fadz0f0kl2hby7h";
  })
  (fetchNuGet {
    pname = "System.IO.Pipelines";
    version = "6.0.3";
    sha256 = "1jgdazpmwc21dd9naq3l9n5s8a1jnbwlvgkf1pnm0aji6jd4xqdz";
  })
  (fetchNuGet {
    pname = "System.Memory";
    version = "4.5.5";
    sha256 = "08jsfwimcarfzrhlyvjjid61j02irx6xsklf32rv57x2aaikvx0h";
  })
  (fetchNuGet {
    pname = "System.Numerics.Vectors";
    version = "4.5.0";
    sha256 = "1kzrj37yzawf1b19jq0253rcs8hsq1l2q8g69d7ipnhzb0h97m59";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "5.0.0";
    sha256 = "02k25ivn50dmqx5jn8hawwmz24yf0454fjd823qk6lygj9513q4x";
  })
  (fetchNuGet {
    pname = "System.Runtime.CompilerServices.Unsafe";
    version = "6.0.0";
    sha256 = "0qm741kh4rh57wky16sq4m0v05fxmkjjr87krycf5vp9f0zbahbc";
  })
  (fetchNuGet {
    pname = "System.Security.AccessControl";
    version = "5.0.0";
    sha256 = "17n3lrrl6vahkqmhlpn3w20afgz09n7i6rv0r3qypngwi7wqdr5r";
  })
  (fetchNuGet {
    pname = "System.Security.Principal.Windows";
    version = "5.0.0";
    sha256 = "1mpk7xj76lxgz97a5yg93wi8lj0l8p157a5d50mmjy3gbz1904q8";
  })
  (fetchNuGet {
    pname = "System.Text.Encoding.CodePages";
    version = "5.0.0";
    sha256 = "1bn2pzaaq4wx9ixirr8151vm5hynn3lmrljcgjx9yghmm4k677k0";
  })
  (fetchNuGet {
    pname = "System.Text.Encodings.Web";
    version = "6.0.0";
    sha256 = "06n9ql3fmhpjl32g3492sj181zjml5dlcc5l76xq2h38c4f87sai";
  })
  (fetchNuGet {
    pname = "System.Text.Json";
    version = "6.0.0";
    sha256 = "1si2my1g0q0qv1hiqnji4xh9wd05qavxnzj9dwgs23iqvgjky0gl";
  })
  (fetchNuGet {
    pname = "System.Threading.Tasks.Extensions";
    version = "4.5.4";
    sha256 = "0y6ncasgfcgnjrhynaf0lwpkpkmv4a07sswwkwbwb5h7riisj153";
  })
  (fetchNuGet {
    pname = "Tmds.LibC";
    version = "0.5.0";
    sha256 = "0370s49yvl0ljkgp01f20l8zy2xn9vmy3zq5ng0r6m052k1w6fvc";
  })
  (fetchNuGet {
    pname = "Ultz.Native.GLFW";
    version = "3.3.3.1";
    sha256 = "0vmara7s38ilvl4lc6a5i9cihq042jx21libgk0gz5svjw357v0l";
  })
  (fetchNuGet {
    pname = "YamlDotNet";
    version = "12.0.2";
    sha256 = "1v1h8a7x6l5gajqp5vcrh1pvxh9j4rxcs9w7razybzfl7h8q2qxi";
  })
]
