name: Update flake.lock

on:
  schedule:
    - cron: "0 7 * * *"
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update-flake:
    if: github.repository == 'Scrumplex/pkgs'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31

      - uses: DeterminateSystems/update-flake-lock@v27
        with:
          commit-msg: "chore(nix): update lockfile"
          pr-title: "chore(nix): update lockfile"
